# Random Forest Tree:

In [73]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [74]:
geopolymer_df = pd.read_csv("Artificial Intelligence-Based Life Cycle Assessment for Sustainable Geopolymer Concrete.csv")
geopolymer_df

,Composition,Ground Granulated Blast-Furnace Slag,Sugarcane Bagasse Ash,Banana Peel Ash,sodium silicate,sodium sulphate,IST(min),FST(min),Comprehensive Strength,Unnamed: 9,Unnamed: 10,Unnamed: 11,FS
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3 days (psi),7 days (psi),28 days (psi),170 degrees for 24 hours (psi),NaN
1,1.0,66.0,19.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.0,68.0,17.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3.0,70.0,15.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4.0,72.0,13.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,56.0,59.0,13.0,13.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,57.0,58.0,13.5,13.5,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,58.0,57.0,14.0,14.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,59.0,56.0,14.5,14.5,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,60.0,55.0,15.0,15.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [75]:
geopolymer_df = geopolymer_df.rename(columns={'Unnamed: 9': 'Comprehensive Strength 7 days(psi)', 'Unnamed: 10': 'Comprehensive Strength 28 days(psi)', 'Unnamed: 11': '170 degrees for 24 hours(psi)'})
geopolymer_df

,Composition,Ground Granulated Blast-Furnace Slag,Sugarcane Bagasse Ash,Banana Peel Ash,sodium silicate,sodium sulphate,IST(min),FST(min),Comprehensive Strength,Comprehensive Strength 7 days(psi),Comprehensive Strength 28 days(psi),170 degrees for 24 hours(psi),FS
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3 days (psi),7 days (psi),28 days (psi),170 degrees for 24 hours (psi),NaN
1,1.0,66.0,19.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.0,68.0,17.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3.0,70.0,15.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4.0,72.0,13.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,56.0,59.0,13.0,13.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,57.0,58.0,13.5,13.5,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,58.0,57.0,14.0,14.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,59.0,56.0,14.5,14.5,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,60.0,55.0,15.0,15.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [76]:
geopolymer_df.drop(geopolymer_df.index[0], inplace=True) 
geopolymer_df

,Composition,Ground Granulated Blast-Furnace Slag,Sugarcane Bagasse Ash,Banana Peel Ash,sodium silicate,sodium sulphate,IST(min),FST(min),Comprehensive Strength,Comprehensive Strength 7 days(psi),Comprehensive Strength 28 days(psi),170 degrees for 24 hours(psi),FS
1,1.0,66.0,19.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.0,68.0,17.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3.0,70.0,15.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4.0,72.0,13.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5.0,74.0,11.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6.0,76.0,9.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7.0,78.0,7.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8.0,80.0,5.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9.0,82.0,3.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10.0,84.0,1.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,11.0,66.0,0.0,19.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,12.0,68.0,0.0,17.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,13.0,70.0,0.0,15.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,14.0,72.0,0.0,13.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,15.0,74.0,0.0,11.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,16.0,76.0,0.0,9.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,17.0,78.0,0.0,7.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,18.0,80.0,0.0,5.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,19.0,82.0,0.0,3.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,20.0,84.0,0.0,1.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,21.0,66.0,9.5,9.5,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,22.0,68.0,8.5,8.5,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,23.0,70.0,7.5,7.5,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,24.0,72.0,6.5,6.5,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,25.0,74.0,5.5,5.5,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,26.0,76.0,4.5,4.5,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,27.0,78.0,3.5,3.5,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,28.0,80.0,2.5,2.5,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,29.0,82.0,1.5,1.5,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,30.0,84.0,0.5,0.5,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,31.0,64.0,21.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,32.0,63.0,22.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,33.0,62.0,23.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,34.0,61.0,24.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,35.0,60.0,25.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,36.0,59.0,26.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,37.0,58.0,27.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,38.0,57.0,28.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,39.0,56.0,29.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,40.0,55.0,30.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,41.0,64.0,0.0,21.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,42.0,63.0,0.0,22.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,43.0,62.0,0.0,23.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,44.0,61.0,0.0,24.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,45.0,60.0,0.0,25.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,46.0,59.0,0.0,26.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,47.0,58.0,0.0,27.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,48.0,57.0,0.0,28.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,49.0,56.0,0.0,29.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,50.0,55.0,0.0,30.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,51.0,64.0,10.5,10.5,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,52.0,63.0,11.0,11.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,53.0,62.0,11.5,11.5,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,54.0,61.0,12.0,12.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,55.0,60.0,12.5,12.5,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,56.0,59.0,13.0,13.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,57.0,58.0,13.5,13.5,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,58.0,57.0,14.0,14.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,59.0,56.0,14.5,14.5,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,60.0,55.0,15.0,15.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Input Values:

In [77]:
geopolymer_df.head()

,Composition,Ground Granulated Blast-Furnace Slag,Sugarcane Bagasse Ash,Banana Peel Ash,sodium silicate,sodium sulphate,IST(min),FST(min),Comprehensive Strength,Comprehensive Strength 7 days(psi),Comprehensive Strength 28 days(psi),170 degrees for 24 hours(psi),FS
1,1.0,66.0,19.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.0,68.0,17.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3.0,70.0,15.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4.0,72.0,13.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5.0,74.0,11.0,0.0,7.5,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
mask_ist = geopolymer_df['IST(min)'].isna()
geopolymer_df.loc[mask_ist, 'IST(min)'] = np.random.uniform(low=30, high=80, size=mask_ist.sum())
geopolymer_df['IST(min)'] = geopolymer_df['IST(min)'].astype(int)

mask_fst = geopolymer_df['FST(min)'].isna()
geopolymer_df.loc[mask_fst, 'FST(min)'] = np.random.uniform(low=30, high=80, size=mask_fst.sum())
geopolymer_df['FST(min)'] = geopolymer_df['FST(min)'].astype(int)

mask_low_cs = geopolymer_df['Comprehensive Strength'].isna()
geopolymer_df.loc[mask_low_cs, 'Comprehensive Strength'] = np.random.uniform(low=10, high=20, size=mask_low_cs.sum())
geopolymer_df['Comprehensive Strength'] = geopolymer_df['Comprehensive Strength'].astype(int)

mask_medium_cs = geopolymer_df['Comprehensive Strength 7 days(psi)'].isna()
geopolymer_df.loc[mask_medium_cs, 'Comprehensive Strength 7 days(psi)'] = np.random.uniform(low=15, high=35, size=mask_medium_cs.sum())
geopolymer_df['Comprehensive Strength 7 days(psi)'] = geopolymer_df['Comprehensive Strength 7 days(psi)'].astype(int)

mask_high_cs = geopolymer_df['Comprehensive Strength 28 days(psi)'].isna()
geopolymer_df.loc[mask_high_cs, 'Comprehensive Strength 28 days(psi)'] = np.random.uniform(low=45, high=80, size=mask_high_cs.sum())
geopolymer_df['Comprehensive Strength 28 days(psi)'] = geopolymer_df['Comprehensive Strength 28 days(psi)'].astype(int)

mask_170_degrees = geopolymer_df['170 degrees for 24 hours(psi)'].isna()
geopolymer_df.loc[mask_170_degrees, '170 degrees for 24 hours(psi)'] = np.random.uniform(low=25, high=40, size=mask_170_degrees.sum())
geopolymer_df['170 degrees for 24 hours(psi)'] = geopolymer_df['170 degrees for 24 hours(psi)'].astype(int)

mask_fs = geopolymer_df['FS'].isna()
geopolymer_df.loc[mask_fs, 'FS'] = np.random.uniform(low=15, high=35, size=mask_fs.sum())
geopolymer_df['FS'] = geopolymer_df['FS'].astype(int)

geopolymer_df.head()

C:\Users\sydne\AppData\Local\Temp\ipykernel_18924\3616810849.py:10: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  geopolymer_df.loc[mask_low_cs, 'Comprehensive Strength'] = np.random.uniform(low=10, high=20, size=mask_low_cs.sum())
C:\Users\sydne\AppData\Local\Temp\ipykernel_18924\3616810849.py:14: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  geopolymer_df.loc[mask_medium_cs, 'Comprehensive Strength 7 days(psi)'] = np.random.uniform(low=15, high=35, size=mask_medium_cs.sum())
C:\Users\sydne\AppData\Local\Temp\ipykernel_18924\3616810849.py:18: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  geopolymer_df.loc[mask_high_cs, 'Comprehensive Strength 28 days(psi)'] = np.random.uniform(low=45, high=80, size=mask_high_cs.sum())
C:\Users\sydne\AppData\Local\Temp\ipykernel_18924\3616810849.py:22: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  geopolymer_df.loc[mask_170_degrees, '170 degrees for 24 hours(psi)'] = np.random.uniform(low=25, high=40, size=mask_170_degrees.sum())

,Composition,Ground Granulated Blast-Furnace Slag,Sugarcane Bagasse Ash,Banana Peel Ash,sodium silicate,sodium sulphate,IST(min),FST(min),Comprehensive Strength,Comprehensive Strength 7 days(psi),Comprehensive Strength 28 days(psi),170 degrees for 24 hours(psi),FS
1,1.0,66.0,19.0,0.0,7.5,7.5,42,78,19,19,70,35,20
2,2.0,68.0,17.0,0.0,7.5,7.5,67,45,19,32,67,30,27
3,3.0,70.0,15.0,0.0,7.5,7.5,58,50,18,26,59,32,16
4,4.0,72.0,13.0,0.0,7.5,7.5,78,36,12,25,46,28,15
5,5.0,74.0,11.0,0.0,7.5,7.5,34,72,17,24,75,32,24

In [79]:
# summary of stats:
geopolymer_df.describe()

,Composition,Ground Granulated Blast-Furnace Slag,Sugarcane Bagasse Ash,Banana Peel Ash,sodium silicate,sodium sulphate,IST(min),FST(min),Comprehensive Strength,Comprehensive Strength 7 days(psi),Comprehensive Strength 28 days(psi),170 degrees for 24 hours(psi),FS
count,60.000000,60.000000,60.000000,60.000000,60.0,60.0,60.000000,60.000000,60.000000,60.0000,60.000000,60.000000,60.000000
mean,30.500000,67.250000,8.875000,8.875000,7.5,7.5,55.250000,57.150000,14.466667,23.5500,61.766667,32.383333,24.066667
std,17.464249,9.058426,9.358955,9.358955,0.0,0.0,13.352617,16.007228,2.994156,5.5797,10.998254,4.392180,6.117124
min,1.000000,55.000000,0.000000,0.000000,7.5,7.5,32.000000,30.000000,10.000000,15.0000,45.000000,25.000000,15.000000
25%,15.750000,59.750000,0.000000,0.000000,7.5,7.5,44.500000,44.500000,12.000000,18.0000,52.750000,28.000000,19.000000
50%,30.500000,65.000000,6.750000,6.750000,7.5,7.5,55.500000,60.500000,14.000000,24.0000,59.000000,32.000000,24.000000
75%,45.250000,74.500000,14.125000,14.125000,7.5,7.5,66.250000,72.000000,17.250000,28.0000,72.000000,36.000000,29.000000
max,60.000000,84.000000,30.000000,30.000000,7.5,7.5,79.000000,79.000000,19.000000,33.0000,79.000000,39.000000,34.000000

# Train and Test Data:

In [88]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [89]:
X = geopolymer_df.iloc[:, 1:6]
y = geopolymer_df.iloc[:, 6:13]

In [90]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [91]:
# Create and train the model
# Key parameters include n_estimators (number of trees) and random_state for reproducibility
rf = RandomForestRegressor(n_estimators=100, random_state=42) 
rf.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [92]:
# Make predictions on the test set
predictions = rf.predict(X_test)
predictions

array([[50.32, 41.3 , 14.97, 29.25, 56.6 , 30.26, 25.71],
       [49.37, 57.01, 15.34, 21.32, 66.41, 32.55, 26.42],
       [59.46, 57.25, 14.49, 19.6 , 61.78, 34.  , 25.62],
       [53.6 , 70.5 , 15.  , 26.09, 62.51, 32.67, 24.42],
       [53.33, 47.56, 14.21, 17.73, 53.75, 33.85, 25.23],
       [50.15, 59.04, 16.26, 23.5 , 59.92, 30.87, 20.2 ],
       [59.95, 53.31, 11.92, 20.99, 62.96, 32.13, 20.33],
       [59.38, 67.82, 14.84, 28.01, 68.26, 30.49, 27.14],
       [61.73, 51.57, 16.54, 18.38, 53.79, 32.15, 27.44],
       [63.99, 49.74, 15.02, 23.27, 61.64, 33.72, 23.95],
       [62.08, 64.49, 14.92, 26.74, 67.83, 29.69, 26.5 ],
       [48.96, 68.54, 14.72, 21.29, 56.15, 33.24, 19.53],
       [50.31, 47.97, 11.67, 23.94, 58.26, 29.92, 22.7 ],
       [50.66, 58.37, 16.53, 24.19, 66.87, 32.63, 22.23],
       [47.93, 64.52, 15.6 , 23.39, 56.56, 31.2 , 18.65],
       [62.76, 65.1 , 12.44, 21.97, 58.28, 32.19, 24.09],
       [67.67, 61.75, 14.99, 26.36, 70.76, 30.61, 27.55],
       [54.78, 50.65, 14.51, 19.19, 66.2 , 32.41, 27.43]])

In [94]:
# Evaluate the model
mse = mean_squared_error(y_test, predictions)
r2 = r2_score(y_test, predictions)
print(f"Mean Squared Error: {mse}") 
print(f"R^2 Error: {r2}")

Mean Squared Error: 143.07931507936505
R^2 Error: -0.40347016392831214

In [95]:
# predicted values in dataframe
df_pred = pd.DataFrame(
    predictions,
    columns=y.columns,
)

df_pred

,IST(min),FST(min),Comprehensive Strength,Comprehensive Strength 7 days(psi),Comprehensive Strength 28 days(psi),170 degrees for 24 hours(psi),FS
0,50.32,41.30,14.97,29.25,56.60,30.26,25.71
1,49.37,57.01,15.34,21.32,66.41,32.55,26.42
2,59.46,57.25,14.49,19.60,61.78,34.00,25.62
3,53.60,70.50,15.00,26.09,62.51,32.67,24.42
4,53.33,47.56,14.21,17.73,53.75,33.85,25.23
5,50.15,59.04,16.26,23.50,59.92,30.87,20.20
6,59.95,53.31,11.92,20.99,62.96,32.13,20.33
7,59.38,67.82,14.84,28.01,68.26,30.49,27.14
8,61.73,51.57,16.54,18.38,53.79,32.15,27.44
9,63.99,49.74,15.02,23.27,61.64,33.72,23.95
10,62.08,64.49,14.92,26.74,67.83,29.69,26.50
11,48.96,68.54,14.72,21.29,56.15,33.24,19.53
12,50.31,47.97,11.67,23.94,58.26,29.92,22.70
13,50.66,58.37,16.53,24.19,66.87,32.63,22.23
14,47.93,64.52,15.60,23.39,56.56,31.20,18.65
15,62.76,65.10,12.44,21.97,58.28,32.19,24.09
16,67.67,61.75,14.99,26.36,70.76,30.61,27.55
17,54.78,50.65,14.51,19.19,66.20,32.41,27.43

# Feature Importance:

In [96]:
feature_importance_df = pd.DataFrame({
    "feature": X_test.columns,
    "importance": model.feature_importances_
})
feature_importance_df

                                feature  importance
0  Ground Granulated Blast-Furnace Slag    0.406311
1                 Sugarcane Bagasse Ash    0.273292
2                       Banana Peel Ash    0.320396
3                       sodium silicate    0.000000
4                       sodium sulphate    0.000000